### PR TITLE
Rewrite the home page with Vitesse

### PR DESCRIPTION
**Pull request by widcardw**
However, I have no permission to modify the repo directly...

Sample page: <https://elegant-pie-49c896.netlify.app/>

### CODE REVIEW

**Comment by widcardw** [comment]
Fix an animation bug: the animationStart event would be passed to child components, which caused the FadeIn animation to shake.

**Comment by TonyCrane** [comment]
可以把 Copyright 固定到底部吗，我打算 merge 了

**Comment by TonyCrane** [comment]
哦以及要写一个 Action workflow 吧

**Comment by widcardw** [comment]
> 

Action 其实不用，因为可以走 netlify 部署

**Pull request merged**
